### ISSUE TITLE
File upload scenario is unflexible.

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/ion-mob-ms#20]
I cannot get the file upload function to work. HEre are the main issues;

1- once i select either a feature file, i cannot select a metadata file, the directory is empty: 
![image](https://user-images.githubusercontent.com/1847866/172244276-4019b625-17cc-476c-9640-0f7f3838962d.png)
2- I cannot see which file i uploaded (so that previous scenario might be reversed)
3- I cannot change what I selected

**Comment by jjacobson95** [comment]
I'll work on documentation to include what each upload type is.  I'll also work to include a confirmation message with parameters and file locations before running each experiment.  Last, I'll change File Upload names/types to be a bit more clear.

1:    "Raw Data", "Feature Data" and "Framemetadata" only allow you to select folders/directories (all individual files are hidden so users can't accidently select them), select the test directory that corresponds to each. "Raw file metadata" is an individual file that is not in the metadata folder, this test file is titled "RawFiles_Metadata.csv". "Calibrant data" is an individual file and the test data is titled "TuneMix-CCS.txt"

2:    This will be partially addressed by including a confirmation message.

3:    I believe you can change what you selected - if you press the same Browse button again, it will overwrite the previous entry. This can be seen with changes to sample.json, but requires some digging...  I think documentation (and the confirmation message) should help address this.  

Last, nothing is SLIM is currently functional - I haven't had any test data to work on this with.
